blank_issues_enabled: false
contact_links:
  - name: Discussions
    url: https://github.com/gabrielpantoja-cl/complemento-excel/discussions
    about: Ask questions and share feedback in GitHub Discussions.
